name: Send a notification to the documentation repository to update the documentation

on:
  release:
    types:
      - created

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Send notification
              run: |
                curl --location "https://api.github.com/repos/Bossy-Romain/AppaLCA_Beta_Doc/dispatches" \
                -H "Accept: application/vnd.github.everest-preview+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer ${{ secrets.PAT }}" \
                --data "{\"event_type\": \"update_documentation\"}"
